#!/bin/sh

path="$HOME/.dotfiles"

if [ -e $path/.git ]; then
    cd $path && git pull
else
    git clone https://github.com/filippo-liverani/dotfiles.git $path
fi

ln -sf $path/xinitrc ~/.xinitrc
ln -sf $path/Xresources ~/.Xresources
ln -sf $path/ackrc ~/.ackrc
ln -sf $path/tmux.conf ~/.tmux.conf
ln -sf $path/tmuxinator ~/.tmuxinator
ln -sf $path/gitconfig ~/.gitconfig
ln -sf $path/gitignore ~/.gitignore
ln -sf $path/gemrc ~/.gemrc
ln -sf $path/mongorc.js ~/.mongorc.js
ln -sf $path/ssh_config ~/.ssh/config
mkdir -p .local/share/applications
ln -sf $path/mimeapps.list ~/.local/share/applications/mimeapps.list
mkdir -p .config/fontconfig
ln -sf $path/fonts.conf ~/.config/fontconfig/fonts.conf
mkdir -p .config/powerline
ln -sf $path/powerline-config.json ~/.config/powerline/config.json
mkdir -p .i3
ln -sf $path/i3-config ~/.i3/config
ln -sf $path/i3status.conf ~/.i3status.conf
mkdir -p .config/xfce4/terminal
ln -sf $path/terminalrc ~/.config/xfce4/terminal/terminalrc

curl https://raw.github.com/filippo-liverani/zolarizedsh/master/bootstrap -L -o - | sh
curl https://raw.github.com/filippo-liverani/simsalavim/master/bootstrap -L -o - | sh
