#!/bin/sh

path="$HOME/.dotfiles"

if [ -e $path/.git ]; then
    cd $path && git pull
else
    git clone https://github.com/filippo-liverani/dotfiles.git $path
fi

ln -sfT $path/xinitrc ~/.xinitrc
ln -sfT $path/Xresources ~/.Xresources
ln -sfT $path/ackrc ~/.ackrc
ln -sfT $path/tmux.conf ~/.tmux.conf
ln -sfT $path/tmuxinator ~/.tmuxinator
ln -sfT $path/gitconfig ~/.gitconfig
ln -sfT $path/gitignore ~/.gitignore
ln -sfT $path/gemrc ~/.gemrc
ln -sfT $path/mongorc.js ~/.mongorc.js
mkdir -p .config/powerline
ln -sfT $path/powerline-config.json ~/.config/powerline/config.json
ln -sfT $path/ssh_config ~/.ssh/config
mkdir -p .config/i3
ln -sfT $path/i3-config ~/.config/i3/config
mkdir -p .config/xfce4/terminal
ln -sfT $path/terminalrc ~/.config/xfce4/terminal/terminalrc

curl https://raw.github.com/filippo-liverani/zolarizedsh/master/bootstrap -L -o - | sh
curl https://raw.github.com/filippo-liverani/simsalavim/master/bootstrap -L -o - | sh
